### ISSUE TITLE
Exception while closing redis connection 

### ISSUE THREAD

**Issue by isoos** [google/dart-neats#153]
```
Error: Bad state: StreamSink is bound to a stream
at _StreamSinkImpl.close (native)
at _Socket.close (native)
at RespClient.close (package:neat_cache/src/providers/resp.dart:224)
at RedisCacheProvider._withResp (package:neat_cache/src/providers/redis.dart:138)
at StackZoneSpecification._registerUnaryCallback.<fn> (unknown location)
```

**Comment by ricardoamador** [comment]
We occasionally hit this issue as well in flutters cocoon service:
```
"Bad state: StreamSink is bound to a stream
#0      _StreamSinkImpl.close (dart:io/io_sink.dart:182:7)
#1      _Socket.close (dart:io-patch/socket_patch.dart:2243:27)
#2      RespClient.close (package:neat_cache/src/providers/resp.dart:224:21)
#3      RedisCacheProvider._withResp (package:neat_cache/src/providers/redis.dart:138:24)
<asynchronous suspension>
#4      _Entry.set (package:neat_cache/neat_cache.dart:194:7)
<asynchronous suspension>
```
