### ISSUE TITLE
yaml_edit: unable to update empty value nodes

### ISSUE THREAD

**Issue by walnutdust** [google/dart-neats#58]
Unable to update an empty node

## Sample Code

```dart
void main() {
  final doc = YamlEditor('''
dependencies:
''');
  doc.update(['dependencies'], {'test': '^1.14.4'});

  print(doc);
}
```

## Stack trace

```
Unhandled exception:
RangeError: Invalid value: Not greater than or equal to 0: -1
#0      RangeError.checkNotNegative (dart:core/errors.dart:376:20)
#1      new SourceEdit._ (package:yaml_edit/src/source_edit.dart:50:16)
#2      new SourceEdit (package:yaml_edit/src/source_edit.dart:43:18)
#3      _replaceInBlockMap (package:yaml_edit/src/map_mutations.dart:172:10)
#4      updateInMap (package:yaml_edit/src/map_mutations.dart:43:14)
#5      YamlEditor.update (package:yaml_edit/src/editor.dart:278:27)
#6      main (file:///home/garett/Development/dart-neats/yaml_edit/example/example.dart:7:7)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by walnutdust** [comment]
Upon inspection, the problem likely occurs with the `span` produced by `package:yaml`'s parsing
